## Use as and integer value in MB (1GB = 1024MB). When free RAM + SWAP
## reaches this value a new SWAP file will be automatically created.
threshold_minimum=1024

## Use as and integer value in MB (1GB = 1024MB). When a SWAP file is
## created it will be this size. The value is divided by 1024 to get
## a Gigabyte value when creating SWAP files.
swap_file_size=2048

## Use as and integer value. The minimmum number of SWAP files that
## will always remain on the system.
required_swap_files=1

## Use as and integer value in MB (1GB = 1024MB). A check will be done
## to ensure that remaining partition space will not be less than this
## after a SWAP file is created.
minimum_free_storage=4096

## Use as an integer value in seconds. How frequently the RAM + SWAP
## usage will be checked.
check_interval=30
